global:
  crypt4ghKey: ""
  egaUsername: ""
  egaPassword: ""
  egaURL: ""
  expirationDays: 14
  iss: ""
  jwtKey: ""
  suprUsername: ""
  suprPassword: ""
  suprURL: ""
  s3url: ""
  uppmaxUsername: ""
  uppmaxPassword: ""

log:
  format: text
  level: debug
