global:
  crypt4ghKey: ""
  egaUser: ""
  egaPassword: ""
  egaUrl: ""
  expirationDays: 14
  iss: ""
  jwtKey: ""
  s3url: ""
  uppmaxUsername: ""
  uppmaxPassword: ""

log:
  format: text
  level: debug
