apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "uppmax-integration.name" . }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "uppmax-integration.name" . }}
                port:
                  number: {{ .Values.service.port }}
  {{ if eq .Values.ingress.protocol "https" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ include "uppmax-integration.name" . }}-ingress-tls
  {{ end }}
