apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uppmax-integration.name" . }}-secret
type: Opaque
stringData:
  uppmaxUsername: {{ .Values.global.uppmaxUsername | quote }}
  uppmaxPassword: {{ .Values.global.uppmaxPassword | quote }}
  egaUser: {{ .Values.global.egaUser | quote }}
  crypt4ghKey: {{ .Values.global.crypt4ghKey }}
  