apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uppmax-integration.name" . }}-secret
type: Opaque
stringData:
  uppmaxUsername: {{ .Values.global.uppmaxUsername | quote }}
  uppmaxPassword: {{ .Values.global.uppmaxPassword | quote }}
  egaUsername: {{ .Values.global.ega.username | quote }}
  egaPassword: {{ .Values.global.ega.password | quote }}
  egaURL: {{ .Values.global.ega.URL | quote }}
  suprUsername: {{ .Values.global.supr.username | quote }}
  suprPassword: {{ .Values.global.supr.password | quote }}
  suprURL: {{ .Values.global.supr.URL | quote }}
  crypt4ghKey: {{ .Values.global.crypt4ghKey }}
  