apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uppmax-integration.name" . }}-secret
type: Opaque
stringData:
  uppmaxUsername: {{ .Values.global.uppmaxUsername | quote }}
  uppmaxPassword: {{ .Values.global.uppmaxPassword | quote }}
  egaUsername: {{ .Values.global.egaUsername | quote }}
  egaPassword: {{ .Values.global.egaPassword | quote }}
  egaURL: {{ .Values.global.egaURL | quote }}
  suprUsername: {{ .Values.global.suprUsername | quote }}
  suprPassword: {{ .Values.global.suprPassword | quote }}
  suprURL: {{ .Values.global.suprURL | quote }}
  crypt4ghKey: {{ .Values.global.crypt4ghKey }}
  