apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uppmax-integration.name" . }}-secret
type: Opaque
stringData:
  iss: {{ .Values.global.iss | quote }}
  pathToKey: {{ .Values.global.pathToKey | quote }}
  uppmaxUsername: {{ .Values.global.uppmaxUsername | quote }}
  uppmaxPassword: {{ .Values.global.uppmaxPassword | quote }}
  s3url: {{ .Values.global.s3url | quote }}
  expirationDays: {{ .Values.global.expirationDays | quote }}
  egaUser: {{ .Values.global.egaUser | quote }}