apiVersion: v1
kind: Service
metadata:
  name: {{ include "uppmax-integration.name" . }}
spec:
  selector:
    app: {{ include "uppmax-integration.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP